# master 配置
master:
  rpcPort: ":9099"
  #addr: "172.18.0.11"
  addr: "127.0.0.1"
  port: ":9099"

# chunk server 配置
chunk:
  port: "6789"
  heartbeat:
   reconnectCount: 5  # heartbeat出问题时的重连次数
   sendTime: 5        # 每隔5s发送一次
  storage:
    path: "./chunks/"

# etcd config
etcd:
  endPoint: "172.18.0.20:2379"

# metrics config
metrics:
  port: "9101"
